---
- name: .net version check
  win_stat:
    path: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'
  register: file_check
- name: check version if file exist
  win_shell: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe -version'
  register: version_check
  when: (file_check.stat.isdir is defined)
- name: version check
  debug:
    msg: "version_check PASSED!!"
  when : version_check.rc == 0
